name: Process New AP Submissions

on:
  issues:
    types: [opened, edited]

permissions:
  contents: write
  pull-requests: write
  issues: read

jobs:
  add-ap-from-issue:
    runs-on: ubuntu-latest
    if: >
      github.event.issue.state == 'open' &&
      (
        startsWith(github.event.issue.title, 'New AP:') ||
        contains(join(github.event.issue.labels.*.name, ','), 'new-ap')
      )

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Extract JSON from issue body and update ap_data.json
        id: update-json
        uses: actions/github-script@v7
        with:
          script: |
            const core = require('@actions/core');
            const github = require('@actions/github');
            const fs = require('fs');
            const path = require('path');

            const issue = github.context.payload.issue;
            const body = issue.body || '';

            // Try to find a ```json ... ``` code block first
            let match = body.match(/```json\s*([\s\S]*?)```/);

            // If no code block, fall back to trying the json_snippet field directly
            if (!match) {
              // Try to find a JSON-looking block in the body
              match = body.match(/\{\s*[\s\S]*\}/);
            }

            if (!match) {
              core.setFailed('No JSON snippet found in issue body. Make sure the JSON snippet field is filled.');
              return;
            }

            const jsonText = match[1] ? match[1].trim() : match[0].trim();
            core.info('Found JSON snippet:');
            core.info(jsonText);

            let ap;
            try {
              ap = JSON.parse(jsonText);
            } catch (err) {
              core.setFailed('Invalid JSON in issue: ' + err.message);
              return;
            }

            // Basic sanity checks
            if (!ap.vendor || !ap.model) {
              core.setFailed('JSON must include at least "vendor" and "model" fields.');
              return;
            }

            const filePath = path.join(process.env.GITHUB_WORKSPACE, 'ap_data.json');
            core.info(`Reading ${filePath}...`);

            const raw = fs.readFileSync(filePath, 'utf8');

            let arr;
            try {
              arr = JSON.parse(raw);
            } catch (err) {
              core.setFailed('ap_data.json is not valid JSON: ' + err.message);
              return;
            }

            if (!Array.isArray(arr)) {
              core.setFailed('ap_data.json is not a JSON array.');
              return;
            }

            arr.push(ap);

            const updated = JSON.stringify(arr, null, 2) + '\n';
            fs.writeFileSync(filePath, updated, 'utf8');

            core.exportVariable('AP_VENDOR', ap.vendor);
            core.exportVariable('AP_MODEL', ap.model);
            core.exportVariable('ISSUE_NUMBER', issue.number.toString());

      - name: Create pull request for new AP
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "Add new AP: ${{ env.AP_VENDOR }} ${{ env.AP_MODEL }}"
          branch: "ap-from-issue-${{ env.ISSUE_NUMBER }}"
          title: "Add new AP from issue #${{ env.ISSUE_NUMBER }}: ${{ env.AP_VENDOR }} ${{ env.AP_MODEL }}"
          body: |
            This PR adds a new AP entry derived from issue #${{ env.ISSUE_NUMBER }}.

            Vendor: **${{ env.AP_VENDOR }}**
            Model: **${{ env.AP_MODEL }}**

            Please review the changes to `ap_data.json` before merging.
          labels: |
            new-ap
